# We don't have to contain all the clients and their usecases since the default behavior is
# setting everything enabled. We only need to make sure the clients and usecases that are
# disabled are all configured.
config_version: 14
client_switches {
    client_id {
        client_application_id: "com.apple.suggestd"
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "classification.classifyMailMessage"
        }
        is_off: false
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "classification.classifyUserNotification"
        }
        is_off: false
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "classification.classifyTextMessage"
        }
        is_off: false
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessage"
        }
        is_off: false
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessageThread"
        }
        is_off: false
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.summarizeTextMessage"
        }
        is_off: false
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.summarizeTextMessageThread"
        }
        is_off: false
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.summarizeUserNotification"
        }
        is_off: false
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.summarizeUserNotificationThread"
        }
        is_off: false
    }
    all_stop: false
}

# iOS mail app
client_switches {
    client_id {
        # iOS mail app
        client_application_id: "com.apple.mobilemail"
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessage"
        }
        is_off: false
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessageThread"
        }
        is_off: false
    }
    all_stop: false
}

# macOS mail app
client_switches {
    client_id {
        client_application_id: "com.apple.mail"
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessage"
        }
        is_off: false
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessageThread"
        }
        is_off: false
    }
    all_stop: false
}

# Text assistant on iOS
client_switches {
    client_id {
        client_application_id: "com.apple.WritingToolsUIService"
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.textAssistant"
        }
        is_off: false
    }
    all_stop: false
}

# Text assistant on MacOS
client_switches {
    client_id {
        client_application_id: "com.apple.WritingTools.xpc.WritingToolsViewService"
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.textAssistant"
        }
        is_off: false
    }
    all_stop: false
}

# SageTool
client_switches {
    client_id {
        client_application_id: "com.apple.GenerativeFunctions.SageTool"
    }
    all_stop: false
}

# summarizationCTL
client_switches {
    client_id {
        client_application_id: "com.apple.SummarizationKit.ctl"
    }
    use_cases {
        use_case_id {
            use_case_unique_name: "summarization.fakeUseCaseID2"
        }
        is_off: true
    }

    all_stop: false
}
block_unconfigured_client: false
