config_version: 34
client_config_list {
    client_id {
        client_application_id: "com.apple.suggestd"
    }
    # The configurations for classification is not used yet
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "classification.classifyMailMessage"
        }
        gms_config {
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "classification.classifyUserNotification"
        }
        gms_config {
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "classification.classifyTextMessage"
        }
        gms_config {
        }
    }
    # The configurations for summarization use cases
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessage"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_moderation]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: [text_moderation]
            }
            summarize_unsafe_input: false
            throw_error_if_final_decision_unsafe: true
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessageThread"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_moderation]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: [text_moderation]
            }
            summarize_unsafe_input: false
            throw_error_if_final_decision_unsafe: true
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.summarizeTextMessage"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_moderation]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 5
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: [text_moderation]
            }
            summarize_unsafe_input: false
            throw_error_if_final_decision_unsafe: true
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.summarizeTextMessageThread"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_moderation]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: [text_moderation]
            }
            summarize_unsafe_input: false
            throw_error_if_final_decision_unsafe: true
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.summarizeUserNotification"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_moderation]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 5
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: [text_moderation]
            }
            summarize_unsafe_input: false
            throw_error_if_final_decision_unsafe: true
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.summarizeUserNotificationThread"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_moderation]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: [text_moderation]
            }
            summarize_unsafe_input: false
            throw_error_if_final_decision_unsafe: true
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.fakeUseCaseID2"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_moderation]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 5
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: [text_moderation]
            }
            summarize_unsafe_input: false
            throw_error_if_final_decision_unsafe: true
        }
    }
}

# Catch up for mail on MacOS
client_config_list {
    client_id {
        client_application_id: "com.apple.mail"
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessage"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_sanitization]
                sanitizer_locale: "en-US"
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: []
                sanitizer_locale: "en-US"
            }
            summarize_unsafe_input: true
            throw_error_if_final_decision_unsafe: false
            final_gms_safety_matrix: [0, 0, 0, 1]
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessageThread"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_sanitization]
                sanitizer_locale: "en-US"
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: []
                sanitizer_locale: "en-US"
            }
            summarize_unsafe_input: true
            throw_error_if_final_decision_unsafe: false
            final_gms_safety_matrix: [0, 0, 0, 1]
        }
    }
}

# Catch up for mail on iOS
client_config_list {
    client_id {
        client_application_id: "com.apple.mobilemail"
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessage"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_sanitization]
                sanitizer_locale: "en-US"
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: []
                sanitizer_locale: "en-US"
            }
            summarize_unsafe_input: true
            throw_error_if_final_decision_unsafe: false
            final_gms_safety_matrix: [0, 0, 0, 1]
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.summarizeMailMessageThread"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_sanitization]
                sanitizer_locale: "en-US"
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: []
                sanitizer_locale: "en-US"
            }
            summarize_unsafe_input: true
            throw_error_if_final_decision_unsafe: false
            final_gms_safety_matrix: [0, 0, 0, 1]
        }
    }
}


# Text assistant on MacOS
client_config_list {
    client_id {
        client_application_id: "com.apple.WritingTools.xpc.WritingToolsViewService"
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.textAssistant"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitTextAssistantInputDenyList"
                active_sanitizers: [text_sanitization]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitTextAssistantOutputDenyList"
                active_sanitizers: []
            }
            summarize_unsafe_input: true
            # final result is marked as safe only when both input and output are safe.
            final_gms_safety_matrix: [0, 0, 0, 1]
        }
    }
}

# Text assistant on iOS
client_config_list {
    client_id {
        client_application_id: "com.apple.WritingToolsUIService"
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.textAssistant"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitTextAssistantInputDenyList"
                active_sanitizers: [text_sanitization]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitTextAssistantOutputDenyList"
                active_sanitizers: []
            }
            summarize_unsafe_input: true
            # final result is marked as safe only when both input and output are safe.
            final_gms_safety_matrix: [0, 0, 0, 1]
        }
    }
}

# Safari reader on MacOS, matches Text Assistant
client_config_list {
    client_id {
        client_application_id: "com.apple.Safari"
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.safariReader"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitTextAssistantInputDenyList"
                active_sanitizers: [text_sanitization]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitTextAssistantOutputDenyList"
                active_sanitizers: []
            }
            summarize_unsafe_input: true
            # final result is marked as safe only when both input and output are safe.
            final_gms_safety_matrix: [0, 0, 0, 1]
        }
    }
}

# Safari reader on iOS, matches Text Assistant
client_config_list {
    client_id {
        client_application_id: "com.apple.mobilesafari"
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.safariReader"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitTextAssistantInputDenyList"
                active_sanitizers: [text_sanitization]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitTextAssistantOutputDenyList"
                active_sanitizers: []
            }
            summarize_unsafe_input: true
            # final result is marked as safe only when both input and output are safe.
            final_gms_safety_matrix: [0, 0, 0, 1]
        }
    }
}


# Notes app (recording) on iOS
client_config_list {
    client_id {
        client_application_id: "com.apple.mobilenotes"
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.notesAudioTranscript.onServer"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_sanitization]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: []
            }
            summarize_unsafe_input: true
            throw_error_if_final_decision_unsafe: false
            final_gms_safety_matrix: [0, 0, 0, 1]
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.notesAudioTranscript.onDevice"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_moderation]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: [text_moderation]
            }
            summarize_unsafe_input: false
            throw_error_if_final_decision_unsafe: true
        }
    }
}

# Notes app (recording) on macOS
client_config_list {
    client_id {
        client_application_id: "com.apple.Notes"
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.notesAudioTranscript.onServer"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_sanitization]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: []
            }
            summarize_unsafe_input: true
            throw_error_if_final_decision_unsafe: false
            final_gms_safety_matrix: [0, 0, 0, 1]
        }
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.notesAudioTranscript.onDevice"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryInputDenyList"
                active_sanitizers: [text_moderation]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 10
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitCUSummaryOutputDenyList"
                active_sanitizers: [text_moderation]
            }
            summarize_unsafe_input: false
            throw_error_if_final_decision_unsafe: true
        }
    }
}

# iOS Magic Paper (there is no MacOS Magic Paper)
client_config_list {
    client_id {
        client_application_id: "com.apple.mobilenotes"
    }
    use_case_config_list {
        use_case_id {
            use_case_unique_name: "summarization.magicPaper"
        }
        gms_config {
            input {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitBaseInputDenyList"
                active_sanitizers: [text_sanitization]
                lang_check_config: {
                    allowed_languages: ["en"]
                    recognizer_max_samples: 5
                }
            }
            output {
                use_deny_list: true
                deny_list_resource_function_name: "SummarizationKitBaseOutputDenyList"
                active_sanitizers: []
            }
            summarize_unsafe_input: false
            throw_error_if_final_decision_unsafe: true
        }
    }
}

